# Generated by Django 3.0.3 on 2020-02-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=6)),
                ('ville', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'horaire',
            },
        ),
        migrations.CreateModel(
            name='JoursSemaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'jours_semaine',
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Adresse')),
                ('heure_debut', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='heure_debut', to='market.Horaire')),
                ('heure_fin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='heure_fin', to='market.Horaire')),
                ('jours_semaine', models.ManyToManyField(blank=True, related_name='jours_Semaine', to='market.JoursSemaine')),
            ],
            options={
                'verbose_name': 'Marché',
                'db_table': 'ref_marche',
            },
        ),
    ]
