# Generated by Django 3.0.3 on 2020-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_du_jour', models.DateField()),
                ('date_f1', models.CharField(max_length=10)),
                ('date_f2', models.CharField(max_length=10)),
                ('date_yyyymm', models.CharField(max_length=6)),
                ('date_yyyymmdd', models.CharField(max_length=8)),
                ('date_yyyy', models.CharField(max_length=4)),
                ('num_mois', models.IntegerField()),
                ('nom_mois', models.CharField(max_length=20)),
                ('nom_jour', models.CharField(max_length=20)),
                ('num_jour_semaine', models.IntegerField()),
                ('num_jour_mois', models.IntegerField()),
                ('num_jour_annee', models.IntegerField()),
                ('num_semaine', models.IntegerField()),
                ('dernier_jour_mois', models.DateField()),
                ('weekend', models.BooleanField()),
            ],
            options={
                'db_table': 'calendrier',
            },
        ),
        migrations.AlterModelTable(
            name='marche',
            table='marche',
        ),
    ]
